[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
glam = { version = "0.23", features = ["serde"] }
derive_more = "0.99"
hecs = "0.9.1"
bitflags = "1.3.2"