[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
message-io = "0.14.6"
bincode = "1.3.3"
glam = { version = "0.22.0", features = ["serde"] }
derive_more = "0.99.17"
hecs = "0.9.1"